language: python
sudo: false
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
env:
  - TOXENV=py27-django1.8
  - TOXENV=py27-django1.9
  - TOXENV=py27-django1.10
  - TOXENV=py34-django1.8
  - TOXENV=py34-django1.9
  - TOXENV=py34-django1.10
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-django1.8
    - python: 3.5
      env: TOXENV=py35-django1.9
    - python: 3.5
      env: TOXENV=py35-django1.10
